## .github/workflows/deploy.yml
#name: Deploy
#
#on:
#  workflow_run:
#    workflows: ["Docker Build"]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH Deploy
#        uses: appleboy/ssh-action@v1.1.0
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            docker pull myorg/springboot-app:latest
#            docker stop springboot || true
#            docker rm springboot || true
#            docker run -d --name springboot -p 8080:8080 myorg/springboot-app:latest
